# このファイルは、DjangoアプリケーションのためのDocker Compose設定ファイルです。
services:
  db1:
    # MySQLデータベースサービスの設定
    image: mysql:8.0
    environment:
      # 環境変数の設定
      MYSQL_DATABASE: archive_system
      MYSQL_USER: archive_system
      MYSQL_PASSWORD: archive_system
      MYSQL_ROOT_PASSWORD: archive_system
    volumes:
      # データ永続化のためのボリューム設定
      - mysql_data1:/var/lib/mysql
    healthcheck:
      # ヘルスチェックの設定
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
    restart: always  # 自動再起動設定

  web:
    # ウェブサービスの設定
    build: .
    volumes:
      # 静的ファイル、設定ファイル、メディアファイルのためのボリューム設定
      - static_volume:/app/staticfiles
      - config_volume:/app/archive_system/config
      - media_volume:/app/media  # メディアボリューム
    ports:
      # ポートのマッピング設定
      - "80:80" # ホスト側のポート:コンテナ側のポート
    depends_on:
      db1:
        condition: service_healthy
    entrypoint: ["/app/entrypoint.sh"]
    deploy:
      resources:
        limits:
          memory: 512M
    restart: always  # 自動再起動設定

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db1
      MYSQL_ROOT_PASSWORD: archive_system
    ports:
      - "8888:80"
    depends_on:
      db1:
        condition: service_healthy

volumes:
  mysql_data1:
  static_volume:
  config_volume:
  media_volume:  # メディアボリューム
    driver: local # ドライバーの指定
    driver_opts:
      type: none  # ドライバータイプの指定
      o: bind # バインドマウントの指定
      device: ./media # メディアボリュームのマウント先の指定
