from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="manager_index"),
    path("write_report", views.write_report, name="write_report"),
    path("reports", views.reports, name="reports"),
    path("report_edit/<int:id>/", views.report_edit, name="report_edit"),
    path("reports_dustbox", views.reports_dustbox, name="reports_dustbox"),
    path("upload", views.upload, name="upload"),
    path("users", views.users, name="users"),
    path("users/add/", views.add_user, name="add_user"),
    path("upload_file", views.upload_file, name="upload_file"),
    path("upload_list", views.upload_list, name="upload_list"),
    path("uploads", views.uploads, name="uploads"),
    path("upload_ocr", views.upload_ocr, name="upload_ocr"),
    path("easy_write_report", views.easy_write_report, name="easy_write_report"),
    path("search_file", views.search_file, name="search_file"),
    path("announcement_create", views.announcement_create, name="announcement_create"),
    path('announcements/', views.announcements, name='announcements'),
    path('announcements/<int:announcement_id>/edit/', views.announcement_edit, name='announcement_edit'),
    path("upload_edit/<int:file_id>/", views.upload_edit, name="upload_edit"), 
    path("upload_gpt", views.upload_gpt, name="upload_gpt"),
    path("upload_ollama", views.upload_ollama, name="upload_ollama"),
    path("upload_ai", views.upload_ai, name="upload_ai"),
    path("tags", views.tags, name="tags"),
    path("tag_detail/<str:name>/", views.tag_detail, name="tag_detail"),
    path('tags/bulk-delete-unused/', views.tags_bulk_delete_unused, name='tags_bulk_delete_unused'),
    path('config', views.config_page, name='config_page'),
    path('uploads_ajax', views.uploads_ajax, name='uploads_ajax'),
    path("uploads_dustbox", views.uploads_dustbox, name="uploads_dustbox"),
    path('upload_ajax', views.upload_ajax, name='upload_ajax'),
    path('categories/', views.category_list, name='category_list'),
    path('categories/create/', views.category_create, name='category_create'),
    path('categories/<int:category_id>/edit/', views.category_edit, name='category_edit'),
    path('categories/<int:category_id>/delete/', views.category_delete, name='category_delete'),
    path('system_info', views.system_info, name='system_info'),
]
