# Generated by Django 5.1.1 on 2024-12-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ArchiveViewer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="file_type",
            field=models.CharField(default="", max_length=255, verbose_name="ファイルタイプ"),
        ),
    ]
