# Generated by Django 5.1.1 on 2024-12-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ArchiveViewer", "0002_upload_file_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="extracted_text",
            field=models.TextField(blank=True, null=True, verbose_name="抽出テキスト"),
        ),
    ]
