# Generated by Django 4.2.5 on 2023-09-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="Eメールアドレス"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, null=True, verbose_name="苗字"),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, null=True, verbose_name="名前"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="有効")),
                ("staff", models.BooleanField(default=False, verbose_name="スタッフ")),
                ("admin", models.BooleanField(default=False, verbose_name="管理者")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
