# Generated by Django 4.2.5 on 2024-07-02 04:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_emailchangerequest"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailChangeRequest",
        ),
    ]
